marketplace/homepage/urls.py
from django.urls import path

from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('sign-up/', views.sign, name='sign')
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('pages/', include('pages.urls')),
]

marketplace/pages/urls.py
from django.urls import path

from pages import views

app_name = 'pages'


urlpatterns = [
    path('marketplace/', views.marketplace, name='marketplace'),
    path('rankings/', views.rankings, name='rankings'),
    path('connect-a-wallet/', views.connect_a_wallet, name='connect_a_wallet'),
]

marketplace/homepage/models.py
from django.db import models

# Create your models here.

marketplace/pages/models.py
from django.db import models

# Create your models here.

marketplace/homepage/views.py
from django.shortcuts import render


def index(request):
    template = 'homepage/index.html'
    return render(request, template, {})


def sign(request):
    template = 'homepage/sign-form.html'
    return render(request, template, {})

marketplace/pages/views.py
from django.shortcuts import render


def marketplace(request):
    template = 'pages/marketplace.html'
    return render(request, template, {})


def rankings(request):
    template = 'pages/rankings.html'
    return render(request, template, {})


def connect_a_wallet(request):
    template = 'pages/connect_a_wallet.html'
    return render(request, template, {})

marketplace/templates/base.html
{% load static %}

<!DOCTYPE html> 
<html lang="en"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
     {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <title>
			{% block title %}
			{% endblock %}
    </title>
  </head>

  <body class="body">
		{% include "includes/header.html" %}
    <main>
      {% block content %}
      {% endblock %}
		</main>
    {% include "includes/footer.html" %}
  </body>

</html>

marketplace/templates/homepage/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  NFT Marketplace
{% endblock %}

{% block content %}
  <section class="head">
    <article class="head__main-info">
      <h1 class="head__title">Discover digital art & Collect NFTs</h1>
      <p class="head__subtitle">NFT marketplace UI created with Anima for Figma. Collect, buy and sell art from more than 20k NFT artists.</p>
      <a href="{% url "homepage:sign" %}">
        <button type="button" class="head__btn">Get Started</button>
      </a>
    </article>
    <div class="head__container">
      <img src="{% static "img/head/head__main-pic.png" %}" class="head__main-pic">
      <p class="head__dis">Space Walking</p>
    </div>
  </section>
{% endblock %}

marketplace/templates/homepage/sign-form.html
{% extends "base.html" %}

{% block title %}
  Sign up
{% endblock %}

{% block content %}
<h1>Form will be here</h1>
{% endblock %}

marketplace/templates/includes/footer.html
<footer class="footer">
	<p class="footer__text">Ⓒ NFT Market. Use this template freely.</p>
</footer>

marketplace/templates/includes/header.html
{% load static %}

<header class="header">
  <a href="{% url "homepage:index" %}" class="header__link">
		<img src="{% static "img/header/header_logo.png" %}" alt="Logo" class="header__logo-img">
		<h2 class="header__logo-text">NFT marketplace</h2>
	</a>
	<nav class="header__menu">
		<ul class="header__list">
			<li class="header__item">
				<a href="{% url "pages:marketplace" %}" class="header__link">Marketplace</a>
			</li>
			<li class="header__item">
				<a href="{% url "pages:rankings" %}" class="header__link">Rankings</a>
			</li>
			<li class="header__item">
				<a href="{% url "pages:connect_a_wallet" %}" class="header__link">Connect a wallet</a>
			</li>
		</ul>
	</nav>
	<a href="{% url "homepage:sign" %}">
	  <button type="button" class="header__btn">Sign Up</button>
	</a>
</header>

marketplace/templates/pages/connect_a_wallet.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Connect a wallet
{% endblock %}

{% block content %}
  <section class="wallet">
    <div class="wallet__container-img">
      <img src="{% static "img/wallet/wallet-img.png" %}" class="wallet__img">
    </div>
    <article class="wallet__article">
      <h2 class="wallet__title">Connect wallet</h2>
      <p class="wallet__subtitle">Choose a wallet you want to connect. There are several wallet providers.</p>
      <nav class="wallet__menu">
        <ul class="wallet__list">
          <li class="wallet__item">
            <a href="#" class="wallet__link">
              <button type="button" class="wallet__btn">Metamask</button>
            </a>
          </li>
          <li class="wallet__item">
            <a href="#" class="wallet__link">
              <button type="button" class="wallet__btn">Wallet Connect</button>
            </a>
          </li>
          <li class="wallet__item">
            <a href="#" class="wallet__link">
              <button type="button" class="wallet__btn">Coinbase</button>
            </a>
          </li>
        </ul>
      </nav>
    </article>
  </section>
{% endblock %}

marketplace/templates/pages/marketplace.html
{% extends "base.html" %}

{% block title %}
  Marketplace
{% endblock %}

{% block content %}
  <section class="marketplace">
    <article class="marketplace__article">
      <h2 class="marketplace__title">Browse Marketplace</h2>
      <p class="marketplace__subtitle">Browse through more than 50k NFTs on the NFT Marketplace.</p>
      <form action="#" class="marketplace__form">
        <input
          type="search"
          maxlength="100"
          placeholder="Search your favourite NFTs"
          class="marketplace__search"
        />
      </form>
    </article>
  </section>
{% endblock %}

marketplace/templates/pages/rankings.html
{% extends "base.html" %}

{% block title %}
  Rankings
{% endblock %}

{% block content %}
  <section class="rankings">
    <article class="rankings__article">
      <h2 class="rankings__title">Top Creators</h2>
      <p class="rankings__subtitle">Check out top ranking NFT artists on the NFT Marketplace.</p>
    </article>
  </section>
{% endblock %}